services:
  frontend:
    platform: linux/amd64
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: journal-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./react-frontend:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ROLLUP_NO_NATIVE=1
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    # image: flask:3.9
    container_name: journal-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: journal-db
    restart: always
    environment:
      POSTGRES_USER: journal_admin
      POSTGRES_PASSWORD: journal_cody
      POSTGRES_DB: journal_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/pg-data:/var/lib/postgresql/data

volumes:
  node_modules: